import { Document, Types } from 'mongoose';

export interface IUser extends Document {
  _id: Types.ObjectId;
  email: string;
  password: string;
  phoneNumber: string;
  current_subscription: Types.ObjectId;
  gender: 'male' | 'female' | 'not_specified';
  profilePicture: string;
  userType: 'parent' | 'sitter' | 'tutor';
  firstName: string;
  wallet: string;
  version: string;
  referredBy: string;
  lastName: string;
  address: string;
  aboutMe: string;
  state: string;
  urlKey: string;
  age: string;
  dateOfBirth: string;
  training: boolean;
  smoker: boolean;
  gardaCheck: 'pending' | 'verified' | 'unverified';
  gardaCheckdoc: string;
  ownCar: boolean;
  country: string;
  noOfChildren: string;
  specialNeeds: string;
  experience: string;
  stripeAcct: string;
  profileSetupComplete: boolean;
  pets: string;
  rate: string;
  device_token: string;
  lessons: Array<string>;
  language: Array<string>;
  firstAid: boolean;
  verification_id: string;
  stripeAccount: { accountName: string; accountNumber: string };
  childcareCertification: string;
  cpr: string;
  ownTransport: boolean;
  availability: 'available' | 'busy' | 'not_available';
  job: 'sitter' | 'au_pair' | 'nanny' | 'tutor';
  lookingFor: 'sitter' | 'au_pair' | 'nanny' | 'tutor';
  verification_satus: 'pending' | 'failed' | 'verified' | 'unverified';
  verificationData: string;
  socialCredentials: object;
  lastLogin: Date;
  status: boolean;
  googleId: string;
  facebookId: string;
  userVerifiedAt: Date;
  childcareCertified: boolean;
  ratings: { reviewCount: number; averageRatings: number };
  blacklist: [];
}
